# Generated by Django 2.2 on 2019-04-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calcium',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrate',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='iron',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='magnesium',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutritional_fiber',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='phosphorus',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='potassium',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sodium',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugar',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_B1',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_B2',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_B3',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_B6',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_C',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
