# Generated by Django 2.2 on 2019-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190412_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(max_length=50000000, null=True),
        ),
    ]
