# Generated by Django 2.2 on 2019-04-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190411_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
