# Generated by Django 2.2 on 2019-04-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190412_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='instructions',
        ),
    ]
