# Generated by Django 2.2 on 2019-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190412_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='overall_time',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
