# Generated by Django 2.2 on 2019-04-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190411_1749'),
        ('api', '0006_auto_20190411_1622'),
    ]

    operations = [
    ]
